on: 
  issues:
    types: [opened, edited]
jobs:
  issue-content:
    runs-on: ubuntu-latest
    steps:
      - name: action
        run: echo "${{ github.event.action }}"
      - name: id
        run: echo "${{ github.event.issue.id }}"
      - name: title
        run: echo "${{ github.event.issue.title }}"
      - name: number
        run: echo "${{ github.event.issue.number }}"
      - name: body
        run: echo "${{ github.event.issue.body }}"
      - name: labels
        run: echo "${{ github.event.issue.labels[0] }}"